# Generated by Django 3.1.4 on 2020-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('birth_country', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('martial_status', models.CharField(max_length=128)),
                ('speaking_english_level', models.CharField(max_length=128)),
                ('education_level', models.CharField(max_length=128)),
                ('been_to_canada', models.BooleanField(default=False)),
                ('monthly_income', models.CharField(max_length=128)),
                ('interested_visa', models.CharField(max_length=128)),
            ],
        ),
    ]
