# Generated by Django 3.1.4 on 2020-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='been_to_canada',
            field=models.CharField(max_length=5),
        ),
    ]
